version: "3.7"

services:
    seizmeia:
        container_name: seizmeia
        command: --reload
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        volumes:
            - ./seizmeia/:/usr/src/app/seizmeia
        ports:
        - "8000:8000"
