name: Publish Docker Image

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-*'

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      # https://stackoverflow.com/questions/58177786
      - name: Get version
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/seizmeia/seizmeia:${{ env.GIT_TAG }}
            ghcr.io/seizmeia/seizmeia:latest
          cache-from: type=registry,ref=ghcr.io/seizmeia/seizmeia:buildcache
          cache-to: type=registry,ref=ghcr.io/seizmeia/seizmeia:buildcache,mode=max
